version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do stylesheet
      -npm install
      -npm run webpack

artifacts:
  files:
   -index.html
   -styles/main.css
   -images/*
   -dist/bundle.js
